### ISSUE TITLE
How can I use the API?

### ISSUE THREAD

**Issue by ghost** [rohithpeddi7/MyBot#1]

**Comment by rohithpeddi7** [comment]
Hello, thanks for reaching out!

This is a desktop app made using tkinter, so I'm afraid it cannot be used on any website. The app basically uses chatgpt api to answer queries of user and also supports some other features like opening apps, searching queries through search engine etc. 

There are many other repos available that have bots that you can integrate onto your website. If you want an easy, low-code option, try tawk.to. 

Hope you find what you are looking for!

Thanks
Rohith
